# sonar-project.properties
sonar.projectKey=fubaritico_react-and-react-native-financial-app
sonar.organization=fubaritico
sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,packages/http-client/src/client/**,packages/prisma/src/generated/**,**/ios/**,**/android/**
