/**
 * @fileoverview Financial App HTTP Client package entry point.
 *
 * This package provides a type-safe HTTP client for the Financial App API,
 * generated from the OpenAPI specification using HeyAPI.
 *
 * **Note**: The `./client` folder is generated by HeyAPI.
 * Run `pnpm generate` to create it.
 *
 * @example
 * ```typescript
 * import { client } from '@financial-app/http-client/client'
 *
 * // Configure once at app startup
 * client.setConfig({
 *   baseUrl: 'http://localhost:3001',
 *   auth: () => accessToken,
 * })
 * ```
 *
 * @example
 * ```typescript
 * // Use with TanStack Query
 * import { getTransactionsOptions, getBalanceOptions } from '@financial-app/http-client'
 * const { data } = useQuery(getTransactionsOptions({ query: { page: 1, limit: 10 } }))
 * ```
 *
 * @see https://heyapi.dev — HeyAPI Documentation
 */

// Re-export generated client
export * from './client'

// Re-export custom types
export type { IApiError } from './types/errors'
